### ISSUE TITLE
Provide Homebrew formula

### ISSUE THREAD

**Issue by erikw** [ozangulle/xdg-urlview#1]
To make this XDG compliant version of urlview available to the general public, it would be great to create a Homebrew formula for it!

This is how the formula for the original urlview looks like:
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/urlview.rb

This cookbook describes how to create and submit a new formula:
https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

**Comment by ozangulle** [comment]
That's a good idea. I don't use Homebrew, however, and I don't have a way of testing it on a Mac.
If anyone wants to do it, I am open for PRs.

To be hones, I would much rather send a PR to the original urlview for this single-feature fork, but that project looks like it's been unmaintained for years.

**Comment by erikw** [comment]
@ozangulle I can take care of creating the Homebrew formula and testing it!

For a formula to work, we would need a git tag at
https://github.com/ozangulle/xdg-urlview/tags
so that github produces a .tar.gz that can be pointed to from the Honebrew formula.

I guess either starting an own semver at `0.1.0` or `1.0.0` for this fork, or include the upstream version this project was forked from like `0.9-22-xdg-1.0.0` (as in version `1.0.0` of the forked upstream `0.9-22`). I'm not sure what is best.

@ozangulle could be you create a git tag, then I'll do the Homebrew formula!

**Comment by ozangulle** [comment]
@erikw I created a tag called [v0.9-xdg-1.0.0](https://github.com/ozangulle/xdg-urlview/releases/tag/v0.9-xdg-1.0.0).
